using Microsoft.AspNetCore.Mvc;
using OrderApp.Application.DTOs;
using OrderApp.Application.Services;

namespace OrderApp.Api.Controllers
{
    [ApiController]
    [Route("api/orders")]
    public class OrdersController : ControllerBase
    {
        private readonly OrderService _orderService;

        public OrdersController(OrderService orderService)
        {
            _orderService = orderService;
        }

        // GET: api/orders/101
        // Load order by typing order number
        [HttpGet("{orderId:int}")]
        public async Task<ActionResult<OrderResponseDto>> GetById(int orderId)
        {
            var (order, fromCache) = await _orderService.GetOrderWithCacheFlagAsync(orderId);
            if (order is null) return NotFound();

            Response.Headers["X-Cache"] = fromCache ? "HIT" : "MISS";

            var dto = await _orderService.MapToResponseDtoAsync(order);
            return Ok(dto);
        }

        // POST: api/orders
        // Create order - OrderId generated by DB
        [HttpPost]
        public async Task<ActionResult<OrderResponseDto>> Create([FromBody] OrderRequestDto request)
        {
            var created = await _orderService.CreateOrderAsync(request);

            // returns 201 + Location header
            return CreatedAtAction(nameof(GetById), new { orderId = created.OrderId }, created);
        }

        // PUT: api/orders/101
        // Update order (replace header + items)
        [HttpPut("{orderId:int}")]
        public async Task<ActionResult<OrderResponseDto>> Update(int orderId, [FromBody] OrderRequestDto request)
        {
            var updated = await _orderService.UpdateOrderAsync(orderId, request);
            if (updated is null) return NotFound(new { message = "Order not found" });

            return Ok(updated);
        }

        // DELETE: api/orders/101
        [HttpDelete("{orderId:int}")]
        public async Task<IActionResult> Delete(int orderId)
        {
            var deleted = await _orderService.DeleteOrderAsync(orderId);
            if (!deleted) return NotFound(new { message = "Order not found" });

            return NoContent();
        }
    }
}
